### ISSUE TITLE
recv_ready error for both replace and merge even though change is commited 

### ISSUE THREAD

**Issue by bvcao** [napalm-automation/napalm-ios#18]
Traceback (most recent call last):
  File "gistfile.py", line 46, in <module>
    main()
  File "gistfile.py", line 42, in main
    device.commit_config()
  File "/usr/lib/python2.7/site-packages/napalm_ios/ios.py", line 209, in commit_config
    output = self._commit_hostname_handler(cmd)
  File "/usr/lib/python2.7/site-packages/napalm_ios/ios.py", line 181, in _commit_hostname_handler
    if current_prompt == self.device.find_prompt():
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 276, in find_prompt
    if self.wait_for_recv_ready():
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 236, in wait_for_recv_ready
    raise NetMikoTimeoutException("Timed out waiting for recv_ready")
netmiko.ssh_exception.NetMikoTimeoutException: Timed out waiting for recv_ready

**Comment by ktbyers** [comment]
This originally occurred on a Cisco 881.

**Comment by ktbyers** [comment]
A lot has changed in Netmiko since this was reported.
